export  {Home } from './Home'
export { NotFound } from './NotFound'
export { Categories } from './Categories'
export { Login } from './Login'
export { CustomerService } from './CustomerService'
export { SignUp } from './SignUp'
export { Products } from './Products'
export { Product } from './Product'
export { Profile } from './Profile'
export { Success } from './Success'
export { Checkout } from './Checkout'