export {Home} from './Home'
export {NotFound} from './NotFound'
export {Categories} from './Categories'
export { Login } from './Login'
export { CustomerService } from './CustomerService'
export { SignUp } from './SignUp'
export { Products } from './Products'
export {ShoppingCart} from './ShoppingCart'
export {Porfile} from './Profile'